(()=>{
  if(window.__vedatorPlayerActions)return;
  window.__vedatorPlayerActions=true;
  const KEY='vedator-user-playlists-v1',A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
  const lang=()=>{try{return window.vedatorUiLanguage?.()==='sk'?'sk':'cz'}catch{return'cz'}},t=(cz,sk)=>lang()==='sk'?sk:cz;
  const epNum=title=>Number(String(title||'').match(/\bpodcast\s+(\d+)\b/i)?.[1]||0);
  const currentNum=()=>epNum(document.querySelector('.vedator-audio-card__title')?.textContent?.trim()||'');
  const enc=n=>Number.isInteger(Number(n))&&Number(n)>=0&&Number(n)<4096?A[(Number(n)>>6)&63]+A[Number(n)&63]:'';
  const dec=s=>{s=String(s||'');if(s.length!==2)return-1;const h=A.indexOf(s[0]),l=A.indexOf(s[1]);return h<0||l<0?-1:(h<<6)|l};
  const matches=(item,n)=>{const d=dec(item);if(d>=0&&d<2048)return d===n;try{const e=Array.isArray(episodes)?episodes.find(x=>String(x?.id||x?.number||x?.title||'')===String(item)):null;return Number(e?.number)===n}catch{return false}};
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}},save=x=>{localStorage.setItem(KEY,JSON.stringify(x));window.dispatchEvent(new CustomEvent('vedatorplaylistchange'))};
  const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(36).slice(2);
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const help=text=>{const x=document.querySelector('.vedator-audio-card__help');if(x)x.textContent=text};

  const style=document.createElement('style');style.textContent=`
  .vedator-custom-secondary.vedator-actions-organized{display:grid!important;grid-template-columns:1fr!important;gap:9px!important}
  .vedator-player-action-row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}
  .vedator-actions-organized .vedator-custom-btn{min-height:58px!important;flex-direction:column!important;gap:3px!important;text-align:center;line-height:1.12;padding:7px 6px!important}
  .vedator-actions-organized .vedator-custom-btn>span{text-align:center}.vedator-actions-organized .vedator-speed-label,.vedator-actions-organized .vedator-playlist-player-label,.vedator-actions-organized .vedator-offline-label,.vedator-actions-organized .download-label{font-size:.78rem;font-weight:800}.vedator-actions-organized .speed-value{font-size:.88rem;font-weight:900}
  .vedator-playlist-player-btn.in-playlist{border-color:#86c79a}html.theme-dark .vedator-playlist-player-btn.in-playlist{border-color:#4ade80}
  .vedator-playlist-picker{position:fixed;inset:0;z-index:12000;display:flex;align-items:center;justify-content:center;padding:18px;background:rgba(3,7,18,.68)}.vedator-playlist-picker.hidden{display:none}
  .vedator-playlist-picker-box{width:min(440px,100%);max-height:min(78vh,680px);display:grid;grid-template-rows:auto minmax(0,1fr) auto;overflow:hidden;background:var(--card);color:var(--ink);border:1px solid var(--line);border-radius:20px;box-shadow:0 20px 60px rgba(0,0,0,.28)}
  .vedator-playlist-picker-head,.vedator-playlist-picker-foot{display:flex;align-items:center;gap:10px;padding:14px 16px}.vedator-playlist-picker-head{border-bottom:1px solid var(--line)}.vedator-playlist-picker-head strong{flex:1}.vedator-playlist-picker-close{border:0;background:transparent;color:var(--muted);font-size:1.25rem;cursor:pointer}.vedator-playlist-picker-list{overflow:auto;padding:10px 14px}.vedator-playlist-picker-item{display:flex;align-items:center;gap:10px;padding:11px 4px;border-bottom:1px solid var(--line);cursor:pointer}.vedator-playlist-picker-item input{width:20px;height:20px}.vedator-playlist-picker-empty{padding:22px 4px;text-align:center;color:var(--muted)}.vedator-playlist-picker-foot{border-top:1px solid var(--line);flex-wrap:wrap;justify-content:flex-end}.vedator-playlist-picker-new,.vedator-playlist-picker-cancel,.vedator-playlist-picker-save{border-radius:11px;padding:10px 13px;font:inherit;font-weight:800;cursor:pointer}.vedator-playlist-picker-new{margin-right:auto;border:1px solid var(--line);background:transparent;color:var(--ink)}.vedator-playlist-picker-cancel{border:1px solid var(--line);background:transparent;color:var(--ink)}.vedator-playlist-picker-save{border:0;background:var(--accent);color:#fff}
  @media(max-width:550px){.vedator-player-action-row{gap:7px}.vedator-actions-organized .vedator-custom-btn{min-height:60px!important;padding:7px 4px!important}.vedator-actions-organized .vedator-speed-label,.vedator-actions-organized .vedator-playlist-player-label,.vedator-actions-organized .vedator-offline-label,.vedator-actions-organized .download-label{font-size:.75rem!important}.vedator-playlist-picker-foot{display:grid;grid-template-columns:1fr 1fr}.vedator-playlist-picker-new{grid-column:1/-1;margin:0}}
  `;document.head.append(style);

  const picker=document.createElement('div');picker.className='vedator-playlist-picker hidden';picker.innerHTML=`<div class="vedator-playlist-picker-box" role="dialog" aria-modal="true"><div class="vedator-playlist-picker-head"><strong class="vedator-playlist-picker-title"></strong><button class="vedator-playlist-picker-close" type="button">✕</button></div><div class="vedator-playlist-picker-list"></div><div class="vedator-playlist-picker-foot"><button class="vedator-playlist-picker-new" type="button"></button><button class="vedator-playlist-picker-cancel" type="button"></button><button class="vedator-playlist-picker-save" type="button"></button></div></div>`;document.body.append(picker);
  const title=picker.querySelector('.vedator-playlist-picker-title'),list=picker.querySelector('.vedator-playlist-picker-list'),btnNew=picker.querySelector('.vedator-playlist-picker-new'),btnCancel=picker.querySelector('.vedator-playlist-picker-cancel'),btnSave=picker.querySelector('.vedator-playlist-picker-save'),btnClose=picker.querySelector('.vedator-playlist-picker-close');let picked=0;
  function renderPicker(){const pls=load();title.textContent=t('Přidat do playlistu','Pridať do playlistu');btnNew.textContent=t('＋ Vytvořit nový playlist','＋ Vytvoriť nový playlist');btnCancel.textContent=t('Zrušit','Zrušiť');btnSave.textContent=t('Uložit změny','Uložiť zmeny');btnClose.setAttribute('aria-label',t('Zavřít','Zavrieť'));list.innerHTML=pls.length?pls.map(p=>`<label class="vedator-playlist-picker-item"><input type="checkbox" data-playlist-id="${esc(p.id)}" ${Array.isArray(p.items)&&p.items.some(x=>matches(x,picked))?'checked':''}><span>${esc(p.name)}</span></label>`).join(''):`<div class="vedator-playlist-picker-empty">${t('Zatím nemáte žádný playlist.','Zatiaľ nemáte žiadny playlist.')}</div>`}
  function openPicker(){picked=currentNum();if(!picked)return help(t('Tuto epizodu se nepodařilo určit.','Túto epizódu sa nepodarilo určiť.'));renderPicker();picker.classList.remove('hidden')}
  function closePicker(){picker.classList.add('hidden');picked=0}
  function createPlaylist(){const name=prompt(t('Název nového playlistu:','Názov nového playlistu:'))?.trim();if(!name)return;const pls=load();if(pls.some(p=>norm(p.name)===norm(name)))return alert(t('Playlist s tímto názvem už existuje.','Playlist s týmto názvom už existuje.'));const r=enc(picked);pls.push({id:uid(),name,items:r?[r]:[]});save(pls);renderPicker();syncPlaylist()}
  function saveMembership(){const r=enc(picked);if(!r)return closePicker();const chosen=new Set([...list.querySelectorAll('input[data-playlist-id]:checked')].map(x=>x.dataset.playlistId)),pls=load(),names=[];for(const p of pls){const items=(Array.isArray(p.items)?p.items:[]).filter(x=>!matches(x,picked));if(chosen.has(String(p.id))){items.push(r);names.push(p.name)}p.items=items}save(pls);closePicker();syncPlaylist();if(names.length===1)help(t(`Epizoda je v playlistu „${names[0]}“.`,`Epizóda je v playliste „${names[0]}“.`));else if(names.length>1)help(t(`Epizoda je v ${names.length} playlistech.`,`Epizóda je v ${names.length} playlistoch.`));else help(t('Epizoda není v žádném playlistu.','Epizóda nie je v žiadnom playliste.'))}
  btnNew.onclick=createPlaylist;btnCancel.onclick=closePicker;btnSave.onclick=saveMembership;btnClose.onclick=closePicker;picker.onclick=e=>{if(e.target===picker)closePicker()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!picker.classList.contains('hidden'))closePicker()});

  function syncLabels(){const s=document.querySelector('.vedator-custom-secondary');if(!s)return;const speed=s.querySelector('.speed');if(speed){let l=speed.querySelector('.vedator-speed-label');if(!l){l=speed.querySelector('.speed-value')?.previousElementSibling||speed.querySelector('span');l?.classList.add('vedator-speed-label')}if(l)l.textContent=t('Rychlost přehrávání','Rýchlosť prehrávania')}const ob=s.querySelector('.vedator-offline-btn'),ol=ob?.querySelector('.vedator-offline-label');if(ol&&!ob.dataset.vedatorBusy)ol.textContent=ob.classList.contains('saved')?t('✓ Uloženo offline','✓ Uložené offline'):t('Uložit offline','Uložiť offline');const dl=s.querySelector('.download-label');if(dl&&!/^(Připravuji|Pripravujem|Stahuji|Sťahujem|Ukládám|Ukladám)/i.test(dl.textContent.trim()))dl.textContent=t('Stáhnout MP3','Stiahnuť MP3');const pl=s.querySelector('.vedator-playlist-player-label');if(pl)pl.textContent=t('Přidat do playlistu','Pridať do playlistu')}
  function syncPlaylist(){const b=document.querySelector('.vedator-playlist-player-btn');if(!b)return;const n=currentNum(),inside=Boolean(n&&load().some(p=>Array.isArray(p.items)&&p.items.some(x=>matches(x,n))));b.classList.toggle('in-playlist',inside);b.title=inside?t('Epizoda je už v některém playlistu. Klepnutím můžete výběr změnit.','Epizóda už je v niektorom playliste. Klepnutím môžete výber zmeniť.'):t('Přidat epizodu do playlistu','Pridať epizódu do playlistu')}
  function organize(){const s=document.querySelector('.vedator-custom-secondary');if(!s)return false;const speed=s.querySelector('.speed'),download=s.querySelector('.download'),offline=s.querySelector('.vedator-offline-btn');if(!speed||!download||!offline)return false;let playlist=s.querySelector('.vedator-playlist-player-btn');if(!playlist){playlist=document.createElement('button');playlist.type='button';playlist.className='vedator-custom-btn vedator-playlist-player-btn';playlist.innerHTML='<span>＋</span><span class="vedator-playlist-player-label">Přidat do playlistu</span>';playlist.onclick=openPicker}let top=s.querySelector('.vedator-player-action-row.top'),bottom=s.querySelector('.vedator-player-action-row.bottom');if(!top){top=document.createElement('div');top.className='vedator-player-action-row top'}if(!bottom){bottom=document.createElement('div');bottom.className='vedator-player-action-row bottom'}top.append(speed,playlist);bottom.append(offline,download);s.append(top,bottom);s.classList.add('vedator-actions-organized');syncLabels();syncPlaylist();const ol=offline.querySelector('.vedator-offline-label'),dl=download.querySelector('.download-label'),ct=document.querySelector('.vedator-audio-card__title');if(ol&&!ol.__full){ol.__full=true;new MutationObserver(()=>queueMicrotask(syncLabels)).observe(ol,{childList:true,characterData:true,subtree:true})}if(dl&&!dl.__full){dl.__full=true;new MutationObserver(()=>queueMicrotask(syncLabels)).observe(dl,{childList:true,characterData:true,subtree:true})}if(ct&&!ct.__playlistAction){ct.__playlistAction=true;new MutationObserver(()=>queueMicrotask(()=>{syncLabels();syncPlaylist()})).observe(ct,{childList:true,characterData:true,subtree:true})}return true}
  if(!organize()){const o=new MutationObserver(()=>{if(organize())o.disconnect()});o.observe(document.body,{childList:true,subtree:true})}
  window.addEventListener('vedatorlanguagechange',()=>queueMicrotask(()=>{syncLabels();syncPlaylist();if(!picker.classList.contains('hidden'))renderPicker()}));window.addEventListener('vedatorplaylistchange',syncPlaylist);
})();