(()=>{
if(window.__vedatorQuestionsView)return;window.__vedatorQuestionsView=true;
const FAQ=[340,337,332,326,319,313,300,295,289,284,278,272,270,263],BATCH=20;
const MAP={'Vše':[],'Vesmír':['vesmir','hvezd','hviezd','planet','galaxi','slunce','slnko','mesic','mesiac','jupiter','kosmolog','rozpin'],'Černé díry':['cerna dira','cierna diera','hawking','singularit'],'Kvantová fyzika':['kvant','superpoz','spleten','previazan','orbital','wimp','vakuu','vakua'],'Relativita a gravitace':['relativ','gravit','casoprostor','casopriestor','rychlost svetla'],'Matematika':['matemat','prvocisl','nekonec','paradox','entrop','laplace','tri teles'],'Biologie a medicína':['vitamin','gen','gmo','mozek','mozog','spánek','spanek','zrcadlov','cvičit','cvicit'],'Technologie':['pocitac','počítač','mikrovln','gps','bater','vodik','vodík','auto','klavesnic','klávesnic','tiktok','kryptom'],'Země a příroda':['zeme','země','ocean','ledovec','sopk','tornado','počas','pocasi','vzduch','mrak','atmosfer'],'Chemie':['atom','molekul','prvek','prvok','helium','deuter','voda','jogurt','zlato'],'Ostatní':['podcast','jazyk','wikipedia','anime','videohry','recept','motiv','právo','pravo','plochozem']};
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),sec=v=>{const p=String(v||'').match(/\d{1,2}:\d{2}(?::\d{2})?/)?.[0].split(':').map(Number);return!p?0:p.length===3?p[0]*3600+p[1]*60+p[2]:p[0]*60+p[1]};
const eps=()=>{try{return Array.isArray(episodes)?episodes:[]}catch{return[]}},ep=n=>eps().find(e=>Number(e.number)===Number(n));
const tabs=document.querySelector('.tabs'),episodesBox=document.querySelector('#episodes'),seriesBox=document.querySelector('#series'),topics=document.querySelector('#topics'),count=document.querySelector('#count'),episodeSort=document.querySelector('#episodeSort'),seriesSort=document.querySelector('#seriesSort'),search=document.querySelector('#search');if(!tabs||!episodesBox||!seriesBox||!topics||!search)return;
const tab=document.createElement('button');tab.type='button';tab.className='tab';tab.dataset.view='questions';tab.textContent='Otázky';const ptab=tabs.querySelector('[data-view="playlists"]');ptab?tabs.insertBefore(tab,ptab):tabs.append(tab);
const qtopics=document.createElement('div');qtopics.className='topics hidden';qtopics.innerHTML=Object.keys(MAP).map((x,i)=>`<button class="topic${i?'':' active'}" data-topic="${esc(x)}">${esc(x)}</button>`).join('');topics.after(qtopics);
const view=document.createElement('section');view.id='questions';view.className='grid hidden';seriesBox.after(view);
const style=document.createElement('style');style.textContent='.faq-question-card{min-height:260px}.faq-question-card .faq-meta{color:var(--muted);font-size:.85rem}.faq-answer{color:#354158;line-height:1.48;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:6;overflow:hidden}.faq-question-card.open .faq-answer{display:block}.faq-answer ul{margin:.35rem 0;padding-left:1.2rem}.faq-more{border:0;background:transparent;color:var(--accent);font-weight:800;padding:6px 0;cursor:pointer}.faq-play{width:100%;border:0;border-radius:10px;padding:9px;background:var(--accent);color:#fff;font-weight:800;cursor:pointer}.faq-question-card mark{background:#ffe56b;color:#171717}.faq-sentinel{grid-column:1/-1;height:1px}html.theme-dark .faq-answer{color:#d7deea}';document.head.append(style);
let all=[],shown=[],rendered=0,topic='Vše',active=false,io;
async function collect(n){if(n===300){try{if(typeof SUMMARIES!=='undefined'&&SUMMARIES?.[300]?.sections)return SUMMARIES[300].sections.map((x,i)=>({episode:n,order:i,time:x.time,title:String(x.title||'').replace(/^\s*\d+\)\s*/,''),points:[...(x.items||[])]}))}catch{}}
const a=document.createElement('article');a.hidden=true;a.innerHTML=`<h2>Podcast ${n}</h2>`;episodesBox.append(a);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const out=[...a.querySelectorAll('.summary-block')].map((b,i)=>({episode:n,order:i,time:b.querySelector('.summary-time')?.textContent||'0:00',title:b.querySelector('.summary-title')?.textContent||`Otázka ${i+1}`,points:[...b.querySelectorAll('li')].map(x=>x.textContent.trim())}));a.remove();return out}
async function load(){for(const n of FAQ)all.push(...await collect(n));all.sort((a,b)=>b.episode-a.episode||a.order-b.order);filter()}
const terms=()=>norm(search.value.trim()).split(/\s+/).filter(Boolean),text=x=>norm(`${x.title} ${x.points.join(' ')}`);
function ok(x){const t=text(x),ts=terms();return(topic==='Vše'||MAP[topic].some(k=>t.includes(norm(k))))&&ts.every(k=>t.includes(k)||String(x.episode).includes(k))}
function hi(s){const ts=terms();if(!ts.length)return esc(s);let out=esc(s);for(const t of ts){const r=new RegExp(`(${t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'ig');out=out.replace(r,'<mark>$1</mark>')}return out}
function card(x,i){const cats=Object.entries(MAP).filter(([n,k])=>n!=='Vše'&&k.some(v=>text(x).includes(norm(v)))).slice(0,3).map(([n])=>`<span class="tag">${esc(n)}</span>`).join('');return`<article class="faq-question-card" data-i="${i}"><div class="faq-meta">Díl ${x.episode} • ${esc(x.time)}</div><h2>${hi(x.title)}</h2><div class="faq-answer"><ul>${x.points.map(p=>`<li>${hi(p)}</li>`).join('')}</ul></div><button class="faq-more">Číst více</button><div class="tags">${cats}</div><div class="links"><button class="faq-play">▶ Přehrát otázku</button></div></article>`}
function more(){if(rendered>=shown.length)return;view.querySelector('.faq-sentinel')?.remove();const end=Math.min(rendered+BATCH,shown.length);view.insertAdjacentHTML('beforeend',shown.slice(rendered,end).map((x,i)=>card(x,rendered+i)).join('')+'<div class="faq-sentinel"></div>');rendered=end;io?.disconnect();const s=view.querySelector('.faq-sentinel');if(s&&rendered<shown.length){io=new IntersectionObserver(e=>{if(e.some(x=>x.isIntersecting))more()},{rootMargin:'500px'});io.observe(s)}}
function filter(){shown=all.filter(ok);rendered=0;view.innerHTML='';if(active)count.textContent=`${shown.length} otázek`;more()}
function show(on){active=on;view.classList.toggle('hidden',!on);qtopics.classList.toggle('hidden',!on);if(!on)return;document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.toggle('active',x===tab));episodesBox.classList.add('hidden');seriesBox.classList.add('hidden');document.querySelector('.vedator-playlist-view')?.classList.remove('active');topics.classList.add('hidden');episodeSort?.classList.add('hidden');seriesSort?.classList.add('hidden');count.textContent=`${shown.length} otázek`;if(!all.length)load()}
tab.onclick=()=>show(true);tabs.querySelectorAll('.tab').forEach(x=>{if(x!==tab)x.addEventListener('click',()=>show(false))});search.addEventListener('input',()=>{if(active)filter()});qtopics.onclick=e=>{const b=e.target.closest('.topic');if(!b)return;topic=b.dataset.topic;qtopics.querySelectorAll('.topic').forEach(x=>x.classList.toggle('active',x===b));filter()};
function play(i){const x=shown[i],e=ep(x.episode);if(!x||!e?.enclosure)return;window.__vedatorQuestionContext={items:shown.map(q=>({episode:q.episode,time:sec(q.time)})),index:i};window.__vedatorRequestedStart={episode:x.episode,time:sec(x.time),createdAt:Date.now()};const a=document.createElement('article');a.hidden=true;a.innerHTML='<h2></h2><div class="links"><a class="primary"></a></div>';a.querySelector('h2').textContent=e.title;const l=a.querySelector('a');l.href=e.enclosure;l.dataset.vedatorEpisodeTitle=e.title;document.body.append(a);l.click();a.remove()}
view.onclick=e=>{const c=e.target.closest('.faq-question-card');if(!c)return;if(e.target.closest('.faq-more')){c.classList.toggle('open');e.target.textContent=c.classList.contains('open')?'Číst méně':'Číst více'}else if(e.target.closest('.faq-play'))play(Number(c.dataset.i))};
function go(d){const c=window.__vedatorQuestionContext;if(!c)return;const ni=c.index+d;if(ni<0||ni>=c.items.length)return;const t=c.items[ni];c.index=ni;const card=document.querySelector('.vedator-audio-card'),audio=card?.querySelector('audio'),n=Number(String(card?.querySelector('.vedator-audio-card__title')?.textContent||'').match(/\b(\d+)\b/)?.[1]);if(n===t.episode&&audio){audio.currentTime=t.time;audio.play().catch(()=>{});return}const i=shown.findIndex(x=>x.episode===t.episode&&sec(x.time)===t.time);if(i>=0)play(i)}
document.addEventListener('click',e=>{const b=e.target.closest('.vedator-question-btn');if(!b||!window.__vedatorQuestionContext)return;e.preventDefault();e.stopImmediatePropagation();go(b.classList.contains('previous-question')?-1:1)},true);
setInterval(()=>{const c=window.__vedatorQuestionContext,r=document.querySelector('.vedator-question-controls');if(!c||!r)return;const p=r.querySelector('.previous-question'),n=r.querySelector('.next-question');if(p)p.disabled=c.index<=0;if(n)n.disabled=c.index>=c.items.length-1},400);
})();