(()=>{
if(window.__vedatorLanguageSwitch)return;window.__vedatorLanguageSwitch=true;
const KEY='vedator-ui-language-v1';let language='sk';try{language=localStorage.getItem(KEY)==='cz'?'cz':'sk'}catch{}
const T={title:{sk:'Vedátorský podcast podľa tém',cz:'Vedátorský podcast podle témat'},eyebrow:{sk:'Neoficiálny tematický katalóg',cz:'Neoficiální tematický katalog'},search:{sk:'Hľadať',cz:'Hledat'},tabs:{episodes:{sk:'Epizódy',cz:'Epizody'},series:{sk:'Série',cz:'Série'},questions:{sk:'Otázky',cz:'Otázky'},playlists:{sk:'Playlisty',cz:'Playlisty'},data:{sk:'Moje dáta',cz:'Moje data'}},options:{new:{sk:'Najnovšie',cz:'Nejnovější'},old:{sk:'Najstaršie',cz:'Nejstarší'},number:{sk:'Podľa čísla dielu',cz:'Podle čísla dílu'},count:{sk:'Podľa počtu dielov',cz:'Podle počtu dílů'},alpha:{sk:'Podľa abecedy',cz:'Podle abecedy'},first:{sk:'Podľa veku prvého dielu',cz:'Podle stáří prvního dílu'}},topics:{'Vše':['Všetko','Vše'],'Všetko':['Všetko','Vše'],'FAQ':['FAQ','FAQ'],'Mimozemský život':['Mimozemský život','Mimozemský život'],'Kosmologie':['Kozmológia','Kosmologie'],'Kozmológia':['Kozmológia','Kosmologie'],'Temná energie':['Tmavá energia','Temná energie'],'Tmavá energia':['Tmavá energia','Temná energie'],'Černé díry':['Čierne diery','Černé díry'],'Čierne diery':['Čierne diery','Černé díry'],'Kvantová fyzika':['Kvantová fyzika','Kvantová fyzika'],'Relativita':['Relativita','Relativita'],'Astronomie':['Astronómia','Astronomie'],'Astronómia':['Astronómia','Astronomie'],'Biologie a medicína':['Biológia a medicína','Biologie a medicína'],'Biológia a medicína':['Biológia a medicína','Biologie a medicína'],'Matematika':['Matematika','Matematika'],'Technologie a AI':['Technológie a AI','Technologie a AI'],'Technológie a AI':['Technológie a AI','Technologie a AI'],'Země a příroda':['Zem a príroda','Země a příroda'],'Zem a príroda':['Zem a príroda','Země a příroda'],'Chemie a materiály':['Chémia a materiály','Chemie a materiály'],'Chémia a materiály':['Chémia a materiály','Chemie a materiály'],'Společnost a psychologie':['Spoločnosť a psychológia','Společnost a psychologie'],'Spoločnosť a psychológia':['Spoločnosť a psychológia','Společnost a psychologie'],'Vesmír':['Vesmír','Vesmír'],'Relativita a gravitace':['Relativita a gravitácia','Relativita a gravitace'],'Relativita a gravitácia':['Relativita a gravitácia','Relativita a gravitace'],'Technologie':['Technológie','Technologie'],'Technológie':['Technológie','Technologie'],'Chemie':['Chémia','Chemie'],'Chémia':['Chémia','Chemie'],'Ostatní':['Ostatné','Ostatní'],'Ostatné':['Ostatné','Ostatní']}};
const style=document.createElement('style');style.textContent='.vedator-header-actions{display:flex;align-items:center;gap:10px}.vedator-language-switch{display:flex;padding:3px;border:1px solid rgba(255,255,255,.42);border-radius:12px;background:rgba(255,255,255,.12)}.vedator-language-switch button{border:0;border-radius:8px;padding:7px 10px;background:transparent;color:rgba(255,255,255,.76);font-weight:850;cursor:pointer}.vedator-language-switch button.active{background:#fff;color:#29205f;box-shadow:0 2px 8px rgba(0,0,0,.16)}@media(max-width:550px){.vedator-header-actions{gap:6px}.vedator-language-switch button{padding:6px 8px}.vedator-language-switch{padding:2px}}';document.head.append(style);
function setText(node,value){if(node&&node.textContent!==value)node.textContent=value}
function installSwitch(){if(document.querySelector('.vedator-language-switch'))return;const header=document.querySelector('header .header-row');if(!header)return;const install=document.querySelector('#installApp'),actions=document.createElement('div'),toggle=document.createElement('div');actions.className='vedator-header-actions';toggle.className='vedator-language-switch';toggle.setAttribute('role','group');toggle.setAttribute('aria-label','Jazyk aplikácie / Jazyk aplikace');toggle.innerHTML='<button type="button" data-lang="sk">SK</button><button type="button" data-lang="cz">CZ</button>';if(install){install.before(actions);actions.append(toggle,install)}else{actions.append(toggle);header.append(actions)}toggle.onclick=e=>{const b=e.target.closest('button[data-lang]');if(b)setLanguage(b.dataset.lang)}}
function topicKey(button){return button.dataset.topic||button.dataset.vedatorTopicKey||button.textContent.trim()}
function translateCount(){const el=document.querySelector('#count');if(!el)return;const raw=el.textContent.trim();let m;if((m=raw.match(/^(?:Nalezeno|Nájdených)\s+(\d+)\s+z\s+(\d+)\s+(?:epizod|epizód)$/i)))setText(el,language==='sk'?`Nájdených ${m[1]} z ${m[2]} epizód`:`Nalezeno ${m[1]} z ${m[2]} epizod`);else if((m=raw.match(/^(?:Nalezeno|Nájdených)\s+(\d+)\s+(?:sérií|serii)$/i)))setText(el,language==='sk'?`Nájdených ${m[1]} sérií`:`Nalezeno ${m[1]} sérií`);else if((m=raw.match(/^(\d+)\s+(?:otázek|otázok)(.*)$/i)))setText(el,(language==='sk'?`${m[1]} otázok`:`${m[1]} otázek`)+m[2]);}
function translateDates(){let list=[];try{list=Array.isArray(episodes)?episodes:[]}catch{}document.querySelectorAll('#episodes article').forEach(article=>{const date=article.querySelector('.date'),title=article.querySelector('h2')?.textContent.trim();if(!date||!title)return;const item=list.find(x=>String(x.title||'').trim()===title);if(!item?.date)return;const parsed=new Date(item.date);if(Number.isNaN(parsed.getTime()))return;setText(date,new Intl.DateTimeFormat(language==='sk'?'sk-SK':'cs-CZ',{day:'numeric',month:'long',year:'numeric'}).format(parsed))})}
function apply(){installSwitch();document.documentElement.lang=language==='sk'?'sk':'cs';document.title=T.title[language];setText(document.querySelector('header h1'),T.title[language]);setText(document.querySelector('header .eyebrow'),T.eyebrow[language]);const search=document.querySelector('#search');if(search&&search.placeholder!==T.search[language])search.placeholder=T.search[language];document.querySelectorAll('.tabs .tab').forEach(b=>{const x=T.tabs[b.dataset.view];if(x)setText(b,x[language])});document.querySelectorAll('.topics .topic').forEach(b=>{const key=topicKey(b);if(!b.dataset.vedatorTopicKey)b.dataset.vedatorTopicKey=key;const x=T.topics[key]||T.topics[b.textContent.trim()];if(x)setText(b,x[language==='sk'?0:1])});document.querySelectorAll('select option').forEach(o=>{const x=T.options[o.value];if(x)setText(o,x[language])});document.querySelectorAll('.vedator-language-switch button').forEach(b=>{const on=b.dataset.lang===language;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});translateCount();translateDates()}
let queued=false,selectInUse=false;document.addEventListener('pointerdown',e=>{if(e.target.closest('select'))selectInUse=true},true);document.addEventListener('change',e=>{if(e.target.matches('select'))setTimeout(()=>{selectInUse=false;scheduleApply()},0)},true);document.addEventListener('focusout',e=>{if(e.target.matches('select'))setTimeout(()=>{selectInUse=false;scheduleApply()},0)},true);
const observer=new MutationObserver(records=>{if(selectInUse)return;if(!records.some(r=>r.addedNodes.length||r.removedNodes.length))return;scheduleApply()});
function observe(){observer.observe(document.body,{childList:true,subtree:true})}
function runApply(){if(selectInUse)return;observer.disconnect();try{apply()}finally{observe()}}
function scheduleApply(){if(queued||selectInUse)return;queued=true;queueMicrotask(()=>{queued=false;runApply()})}
function setLanguage(next){language=next==='cz'?'cz':'sk';try{localStorage.setItem(KEY,language)}catch{}selectInUse=false;runApply();window.dispatchEvent(new CustomEvent('vedatorlanguagechange',{detail:{language}}))}
window.vedatorUiLanguage=()=>language;runApply();
})();
