import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const data=JSON.parse(fs.readFileSync('content-v2.json','utf8'));
const html=fs.readFileSync('index.html','utf8').replace('<script src="./app-v2.js" defer></script>','');
const dom=new JSDOM(html,{url:'https://example.test/index.html#ask',runScripts:'outside-only',pretendToBeVisual:true});
const {window:w}=dom,d=w.document;
w.localStorage.setItem('vedator-ui-language-v1','cz');
const savedProgress=JSON.stringify({'episode-142':{currentTime:600,duration:1800,completed:false}}),savedPlaylists=JSON.stringify([{id:'saved',name:'Zachovat',items:['CO','Zq']}]);
w.localStorage.setItem('vedatorPlaybackProgressV1',savedProgress);w.localStorage.setItem('vedator-user-playlists-v1',savedPlaylists);
for(const script of d.querySelectorAll('script:not([src])'))w.eval(script.textContent);
let requests=0;w.fetch=async()=>{requests++;return{ok:true,json:async()=>data}};
w.HTMLMediaElement.prototype.play=()=>Promise.resolve();w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLMediaElement.prototype.load=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
const ready=new Promise(resolve=>w.addEventListener('vedator-v2-ready',resolve,{once:true}));
w.eval(fs.readFileSync('app-v2.js','utf8'));d.dispatchEvent(new w.Event('DOMContentLoaded'));await ready;
await new Promise(resolve=>setTimeout(resolve,50));
assert.equal(d.querySelector('.tab-v2.active').dataset.view,'ask');
const waitFor=async(predicate,timeout=20000)=>{const started=Date.now();while(!predicate()){if(Date.now()-started>timeout)throw new Error('Timed out waiting for Ask index');await new Promise(resolve=>setTimeout(resolve,20))}};
assert(['1',undefined].includes(d.documentElement.dataset.vedatorAskLoading)||d.documentElement.dataset.vedatorAskReady==='1');
if(d.documentElement.dataset.vedatorAskLoading==='1'){
 assert(/\d+\s*%/.test(d.querySelector('#ask-status-v2').textContent),'Loading percentage must be visible');
 d.querySelector('.tab-v2[data-view="playlists"]').click();assert.equal(d.querySelector('.tab-v2.active').dataset.view,'playlists','Other tabs must stay responsive while Ask indexes');
 d.querySelector('.tab-v2[data-view="ask"]').click();
}
await waitFor(()=>d.documentElement.dataset.vedatorAskReady==='1');
assert.equal(d.querySelector('#search-v2').placeholder,'Může světlo uniknout z černé díry?');
assert.equal(w.localStorage.getItem('vedatorPlaybackProgressV1'),savedProgress);assert.equal(w.localStorage.getItem('vedator-user-playlists-v1'),savedPlaylists);
assert.equal(d.querySelectorAll('.tab-v2').length,7);
assert.equal(d.querySelectorAll('#ask-results-v2 article').length,0);
assert(!d.querySelector('.panel .controls').classList.contains('hidden'));
assert.equal(d.querySelectorAll('#ask-heading-v2,#ask-note-v2,[data-ask-suggestion]').length,0);
const askIntro=d.querySelector('#ask-intro-v2');
assert(askIntro,'Ask helper sentence missing');
assert(!askIntro.classList.contains('hidden'),'Ask helper sentence must be visible before the first search');
assert(!askIntro.closest('.panel'),'Ask helper sentence must sit outside the top panel');
assert.equal(askIntro.previousElementSibling?.classList.contains('panel'),true,'Ask helper sentence must be directly below the top panel');
assert(askIntro.textContent.includes('Vedátoři'),'Ask helper sentence has wrong Czech text');
assert.equal(d.querySelector('#ask-status-v2').textContent,'');
const askFilterRow=d.querySelector('#parity-topics-v2');
assert(askFilterRow.closest('.panel'),'Ask filters must live inside the same panel as the main tabs');
assert([...askFilterRow.querySelectorAll('.ask-filter-v2')].every(button=>button.classList.contains('topic-v2')),'Ask filters must reuse episode topic pill styling');
assert(d.querySelector('#ask-submit-v2').closest('.controls'));
assert.equal(d.querySelectorAll('[data-ask-filter]').length,3);
const input=d.querySelector('#search-v2'),submitButton=d.querySelector('#ask-submit-v2');
const submit=query=>{input.value=query;submitButton.click()};
input.value='foton';input.dispatchEvent(new w.Event('input',{bubbles:true}));
assert.equal(d.querySelectorAll('#ask-results-v2 article').length,0,'Search must wait for confirmation');
assert(!askIntro.classList.contains('hidden'),'Helper sentence must remain visible while typing before search confirmation');
submit('foton');
assert(askIntro.classList.contains('hidden'),'Helper sentence must disappear after confirmed search');
d.querySelector('#search-clear-v2').click();assert.equal(d.querySelectorAll('#ask-results-v2 article').length,0,'Clear button must clear confirmed ask results');
assert(!askIntro.classList.contains('hidden'),'Helper sentence must return after clearing the confirmed search');
submit('foton');assert(d.querySelectorAll('#ask-results-v2 article').length>0);
const first=d.querySelector('#ask-results-v2 article');
assert(first.querySelector('h2 mark.ask-search-hit'),'Title keywords are not highlighted');
assert(d.querySelector('#ask-results-v2 .ask-answer-v2 mark.ask-search-hit'),'Answer keywords are not highlighted');
assert.equal(first.querySelector('.play').textContent,'▶ Přehrát');
const play=first.querySelector('.play');assert(Number.isFinite(Number(play.dataset.seconds)));
play.click();await new Promise(resolve=>setTimeout(resolve,50));assert(!d.querySelector('#player-v2').classList.contains('hidden'));
assert(d.querySelector('#audio-v2').src.includes(data.episodes.find(e=>Number(e.number)===Number(play.dataset.episode)).enclosure));
const more=first.querySelector('[data-ask-answer]');if(more){more.click();assert(d.querySelector('#ask-results-v2 article').classList.contains('ask-open-v2'))}
for(const filter of ['question','nonquestion']){
 d.querySelector('[data-ask-filter="'+filter+'"]').click();
 assert.equal(d.querySelector('#parity-topics-v2 .ask-filter-v2.active')?.dataset.askFilter,filter,'Active Ask filter must move to the selected pill');
 assert.equal(d.querySelectorAll('#parity-topics-v2 .ask-filter-v2.active').length,1,'Only one Ask filter may be active');
 for(const item of d.querySelectorAll('#ask-results-v2 article'))assert(item.dataset.askId.startsWith(filter==='question'?'q:':'n:'));
}
d.querySelector('[data-ask-filter="all"]').click();
assert.equal(d.querySelector('#parity-topics-v2 .ask-filter-v2.active')?.dataset.askFilter,'all','All must become active again');
submit('černá díra');const synonyms=d.querySelectorAll('#ask-results-v2 article').length;assert(synonyms>0);
submit('black hole');assert(d.querySelector('#ask-results-v2 mark.ask-search-hit'),'Synonyms must be highlighted');assert(d.querySelectorAll('#ask-results-v2 article').length>0,'English synonym should match');
submit('qxzvabcnevermatch');assert.equal(d.querySelectorAll('#ask-results-v2 article').length,0);
submit('');assert.equal(d.querySelectorAll('#ask-results-v2 article').length,0);
input.value='foton';input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert(d.querySelectorAll('#ask-results-v2 article').length>0);
const remembered=input.value;d.querySelector('.tab-v2[data-view="playlists"]').click();assert(!d.querySelector('.panel .controls').classList.contains('hidden'));
d.querySelector('.tab-v2[data-view="ask"]').click();assert.equal(input.value,remembered);
d.querySelector('[data-lang="sk"]').click();assert.equal(d.querySelector('.tab-v2[data-view="ask"]').textContent,'Spýtaj sa');assert.equal(d.querySelector('#ask-submit-v2').textContent,'Hľadať');
assert.equal(requests,1,'Ask tab must reuse loaded data');
const target=d.querySelector('#ask-results-v2 article a').getAttribute('href');w.location.hash=target;
await new Promise(resolve=>setTimeout(resolve,30));assert(['questions','nonquestions'].includes(d.querySelector('.tab-v2.active').dataset.view));
d.querySelector('.tab-v2[data-view=ask]').click();assert.equal(w.location.hash,target);d.querySelector('#ask-results-v2 article a').click();
await new Promise(resolve=>setTimeout(resolve,30));assert(['questions','nonquestions'].includes(d.querySelector('.tab-v2.active').dataset.view),'Repeated catalog link must reopen the answer');
assert.equal(d.querySelector('#ask-submit-v2').classList.contains('hidden'),true);
assert(!d.body.textContent.includes('Napiš otázku a zjisti'));
console.log(JSON.stringify({ok:true,tabPosition:5,confirmedSearch:true,synonyms:true,filters:true,sharedPlayer:true,sharedDataRequests:requests,languageSwitch:true,catalogDeepLink:true}));dom.window.close();
